networks:
  testnet:

services:
  android-emulator:
    image: budtmo/docker-android:emulator_11.0
    container_name: android-container
    ports:
      - "6080:6080"
      - "4723:4723"
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S10
      - WEB_VNC=true
      - APPIUM=true
    platform: linux/amd64
    networks:
      - testnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4723/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 10

  test-runner:
    container_name: mobile-test-runner
    build:
      context: .
    depends_on:
      android-emulator:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - testnet
