services:
  petstore-api:
    image: swaggerapi/petstore3:unstable
    container_name: petstore-api
    ports:
      - "8080:8080"
    networks:
      - testnet
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/api/v3/user || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  api-tests:
    build:
      context: .
    depends_on:
      petstore-api:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - testnet
    volumes:
      - ./build/allure-results:/app/build/allure-results

networks:
  testnet:
