name: API Tests for Petstore

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Grant permission to gradlew
        run: chmod +x ./gradlew
        working-directory: petstore-api-tests

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck
        working-directory: petstore-api-tests

      - name: Run tests with Docker Compose
        run: docker compose up --build --abort-on-container-exit
        working-directory: petstore-api-tests

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: petstore-api-tests/build/reports/allure-report

      - name: Tear down containers
        if: always()
        run: docker compose down -v --remove-orphans
        working-directory: petstore-api-tests