name: Mobile Tests for Monefy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mobile-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Grant permission to gradlew
        run: chmod +x ./gradlew
        working-directory: monefy-mobile-tests

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck
        working-directory: monefy-mobile-tests

      - name: Start Android Emulator on macOS
        run: |
          echo "Starting emulator..."
          $ANDROID_HOME/emulator/emulator -avd Pixel_5_API_30 -no-snapshot -no-audio -no-boot-anim -netdelay none -netspeed full > /dev/null 2>&1 &
          
          echo "Waiting for emulator to boot..."
          until [[ "$($ANDROID_HOME/platform-tools/adb shell getprop sys.boot_completed | tr -d '\r')" == "1" ]]; do
            sleep 5
          done

          echo "Emulator is ready!"
        shell: bash

      - name: Start Appium Server
        run: |
          echo "Starting Appium..."
          nohup appium --log-level info > appium.log 2>&1 &
          sleep 15
        shell: bash

      - name: Run Mobile Tests
        run: ./gradlew test -Dspring.profiles.active=ci
        working-directory: monefy-mobile-tests

      - name: Generate Allure Report
        run: ./gradlew allureReport
        working-directory: monefy-mobile-tests

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: monefy-mobile-tests/build/reports/allure-report

      - name: Copy Allure Report to publish folder
        run: |
          mkdir -p public/mobile
          cp -r monefy-mobile-tests/build/reports/allure-report/* public/mobile/

      - name: Deploy Mobile Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          publish_branch: gh-pages
          force_orphan: false
